version: 2.1

executors:
  php_node:
    docker:
      - image: cimg/php:8.3-node
        environment:
          APP_ENV: testing
          DB_CONNECTION: mysql
          DB_DATABASE: laravel_test
          DB_USERNAME: root
          DB_PASSWORD: root
      - image: cimg/mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel_test

jobs:
  build:
    executor: php_node
    steps:
      - checkout

      # Install dependencies
      - run: sudo apt-get update && sudo apt-get install -y unzip libzip-dev libpng-dev libonig-dev
      - run: sudo docker-php-ext-install pdo_mysql zip

      # Setup composer
      - run: composer install -n --prefer-dist

      # Setup Node
      - run: npm install
      - run: npm run build

      # Generate key & run migration
      - run: cp .env.testing .env
      - run: php artisan key:generate
      - run: php artisan migrate

      # Run tests (jika ada)
      # - run: php artisan test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
