version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/php:8.3-node
        environment:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: laravel
          DB_USERNAME: root
          DB_PASSWORD: secret
      - image: cimg/mysql:8.0
        environment:
          MYSQL_DATABASE: laravel
          MYSQL_ROOT_PASSWORD: secret

jobs:
  test:
    executor: docker-executor
    steps:
      - checkout
      - run: composer install
      - run: npm install
      - run: cp .env.testing .env
      - run: php artisan key:generate
      - run: php artisan migrate --force
      - run: npm run build
      - run: ./vendor/bin/phpunit

  build-and-push:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Build Docker image
          command: |
            docker build -t $DOCKERHUB_USER/laravel-breeze-react:latest .

      - run:
          name: Login to Docker Hub
          command: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin

      - run:
          name: Push Docker image
          command: docker push $DOCKERHUB_USER/laravel-breeze-react:latest


workflows:
  version: 2
  build-test-deploy:
    jobs:
      - test
      - build-and-push:
          requires:
            - test
